apiVersion: v1
kind: Service
metadata:
  name: retrohub-backend-service
  namespace: "2401125"
spec:
  type: ClusterIP
  selector:
    app: retrohub-backend
  ports:
    - port: 5001
      targetPort: 5001
