apiVersion: v1
kind: Service
metadata:
  name: retrohub-frontend-service
  namespace: "2401125"
spec:
  type: ClusterIP   # <-- changed from LoadBalancer â†’ ClusterIP for Ingress routing
  selector:
    app: retrohub-frontend
  ports:
    - port: 80
      targetPort: 80
