apiVersion: v1
kind: Service
metadata:
  name: retrohub-frontend-service
  namespace: "2401125"
spec:
  type: LoadBalancer
  selector:
    app: retrohub-frontend
  ports:
    - port: 80
      targetPort: 80
