apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrohub-frontend
  namespace: "2401125"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrohub-frontend
  template:
    metadata:
      labels:
        app: retrohub-frontend
    spec:
      imagePullSecrets:
        - name: nexus-creds   # <-- using admin-provided Nexus creds
      containers:
        - name: retrohub-frontend
          image: 127.0.0.1:30085/2401125/retrohub-frontend:v2 # <-- Nexus image unchanged
          ports:
            - containerPort: 80   # <-- frontend served at port 80
